Changed comments and meta data

diff --git a/init b/init
--- a/init
+++ b/init
@@ -10,17 +10,6 @@
 # Description:        nginx Linux Standards Base compliant init script.
 ### END INIT INFO
 
-# ----------------------------------------------------------------------------------------------------------------------
-# nginx Linux Standards Base compliant SysVinit script.
-#
-# @link https://wiki.debian.org/LSBInitScripts
-# @link http://paste.ubuntu.com/6918156/
-# @link http://tldp.org/LDP/abs/html/exitcodes.html
-# @author Richard Fussenegger <fleshgrinder@users.noreply.github.com>
-# @copyright 2013-15 Richard Fussenegger
-# @license http://unlicense.org/ PD
-# ----------------------------------------------------------------------------------------------------------------------
-
 
 # ----------------------------------------------------------------------------------------------------------------------
 #                                                                                                              Variables
@@ -45,8 +34,6 @@ VERBOSE=no
 
 # ----------------------------------------------------------------------------------------------------------------------
 #                                                                                                            Error Codes
-#
-# SEE: http://refspecs.linuxfoundation.org/LSB_3.1.0/LSB-Core-generic/LSB-Core-generic/iniscrptact.html
 # ----------------------------------------------------------------------------------------------------------------------
 
 
@@ -68,45 +55,45 @@ readonly EC_STOP_FAILED=154
 # Exit the script with an error code.
 die()
 {
-    log_end_msg $1
-    exit $1
+	log_end_msg $1
+	exit $1
 }
 
 # End the script.
 end()
 {
-    [ "${VERBOSE}" != no ] && log_end_msg 0
-    exit 0
+	[ "${VERBOSE}" != no ] && log_end_msg 0
+	exit 0
 }
 
 # Display failure message.
 fail()
 {
-    log_failure_msg "${NAME}" "$1"
+	log_failure_msg "${NAME}" "$1"
 }
 
 # Display informational message.
 info()
 {
-    [ "${VERBOSE}" != no ] && log_daemon_msg "${NAME}" "$1"
+	[ "${VERBOSE}" != no ] && log_daemon_msg "${NAME}" "$1"
 }
 
 # Display success message.
 ok()
 {
-    [ "${VERBOSE}" != no ] && log_success_msg "${NAME}" "$1"
+	[ "${VERBOSE}" != no ] && log_success_msg "${NAME}" "$1"
 }
 
 # Display warning message.
 warn()
 {
-    log_warning_msg "${NAME}" "$1"
+	log_warning_msg "${NAME}" "$1"
 }
 
 # Print usage string.
 usage()
 {
-    printf 'Usage: %s {start|stop|restart|try-restart|reload|force-reload|status}\n' "$0"
+	printf 'Usage: %s {start|stop|restart|try-restart|reload|force-reload|status}\n' "$0"
 }
 
 ###
@@ -117,11 +104,11 @@ usage()
 ###
 check_privileges()
 {
-    if [ $(id -u) -ne 0 ]
-    then
-        fail 'super user only!'
-        die ${EC_SUPER_USER_ONLY}
-    fi
+	if [ $(id -u) -ne 0 ]
+	then
+		fail 'super user only!'
+		die ${EC_SUPER_USER_ONLY}
+	fi
 }
 
 ###
@@ -133,7 +120,7 @@ check_privileges()
 ###
 reload_service()
 {
-    start-stop-daemon --stop --signal HUP ${SSD_OPTIONS}
+	start-stop-daemon --stop --signal HUP ${SSD_OPTIONS}
 }
 
 ###
@@ -145,7 +132,7 @@ reload_service()
 ###
 start_service()
 {
-    start-stop-daemon --start ${SSD_OPTIONS} -- ${DAEMON_ARGS}
+	start-stop-daemon --start ${SSD_OPTIONS} -- ${DAEMON_ARGS}
 }
 
 ###
@@ -157,7 +144,7 @@ start_service()
 ###
 stop_service()
 {
-    start-stop-daemon --stop --signal QUIT --retry=TERM/30/KILL/5 ${SSD_OPTIONS}
+	start-stop-daemon --stop --signal QUIT --retry=TERM/30/KILL/5 ${SSD_OPTIONS}
 }
 
 
@@ -168,7 +155,7 @@ stop_service()
 
 # Load the VERBOSE setting and other rcS variables plus any script defaults.
 for INCLUDE in /lib/init/vars.sh /etc/default/${NAME}
-    do [ -r "${INCLUDE}" ] && . "${INCLUDE}"
+	do [ -r "${INCLUDE}" ] && . "${INCLUDE}"
 done
 
 # Make all variables which are allowed to be altered by the defaults file as read-only.
@@ -185,21 +172,21 @@ readonly PIDFILE
 INCLUDE=/lib/lsb/init-functions
 if [ -r "${INCLUDE}" ]
 then
-    . "${INCLUDE}"
+	. "${INCLUDE}"
 else
-    printf '%s: unable to load LSB functions, cannot start service.\n' "${NAME}" 1>&2
-    exit ${EC_DAEMON_NOT_FOUND}
+	printf '%s: unable to load LSB functions, cannot start service.\n' "${NAME}" 1>&2
+	exit ${EC_DAEMON_NOT_FOUND}
 fi
 
 # Make sure only one argument was passed to the script.
 if [ $# -ne 1 ]
 then
-    if [ $# -lt 1 -o "$1" = '' ]
-        then fail 'action not specified.'
-        else fail 'too many arguments.'
-    fi
-    usage 1>&2
-    die ${EC_INVALID_ARGUMENT}
+	if [ $# -lt 1 -o "$1" = '' ]
+		then fail 'action not specified.'
+		else fail 'too many arguments.'
+	fi
+	usage 1>&2
+	die ${EC_INVALID_ARGUMENT}
 fi
 readonly ACTION="$1"
 
@@ -207,14 +194,14 @@ readonly ACTION="$1"
 readonly DAEMON=$(command -v "${NAME}")
 if [ ! -x "${DAEMON}" ]
 then
-    if [ "${ACTION}" = 'stop' ]
-    then
-        warn 'executable not found: stop request ignored'
-        end
-    else
-        fail "executable not found: cannot ${ACTION} service"
-        die ${EC_DAEMON_NOT_FOUND}
-    fi
+	if [ "${ACTION}" = 'stop' ]
+	then
+		warn 'executable not found: stop request ignored'
+		end
+	else
+		fail "executable not found: cannot ${ACTION} service"
+		die ${EC_DAEMON_NOT_FOUND}
+	fi
 fi
 
 # Default options for start-stop-daemon command.
@@ -238,85 +225,85 @@ readonly STATUS=$?
 
 case "$1" in
 
-    # Reload the configuration, if the service is running, otherwise do nothing.
-    force-reload|reload)
-        if [ ${STATUS} -eq 0 ]
-        then
-            info 'reloading configuration ...'
-            reload_service || die ${EC_RELOADING_FAILED}
-        else
-            info 'service not running, nothing to be done.'
-        fi
-    ;;
+	# Reload the configuration, if the service is running, otherwise do nothing.
+	force-reload|reload)
+		if [ ${STATUS} -eq 0 ]
+		then
+			info 'reloading configuration ...'
+			reload_service || die ${EC_RELOADING_FAILED}
+		else
+			info 'service not running, nothing to be done.'
+		fi
+	;;
 
-    # Restart the service, if the service is already running, otherwise start the service.
-    restart)
-        if [ ${STATUS} -eq 0 ]
-        then
-            info 'restarting service ...'
-            stop_service || die ${EC_RESTART_STOP_FAILED}
-            sleep 0.1
-        fi
-        start_service || die ${EC_RESTART_START_FAILED}
-    ;;
+	# Restart the service, if the service is already running, otherwise start the service.
+	restart)
+		if [ ${STATUS} -eq 0 ]
+		then
+			info 'restarting service ...'
+			stop_service || die ${EC_RESTART_STOP_FAILED}
+			sleep 0.1
+		fi
+		start_service || die ${EC_RESTART_START_FAILED}
+	;;
 
-    # Start the service, do nothing if it is already running.
-    start)
-        if [ ${STATUS} -eq 0 ]
-        then
-            ok 'already started.'
-        else
-            info 'starting ...'
-            start_service || die ${EC_START_FAILED}
-        fi
-    ;;
+	# Start the service, do nothing if it is already running.
+	start)
+		if [ ${STATUS} -eq 0 ]
+		then
+			ok 'already started.'
+		else
+			info 'starting ...'
+			start_service || die ${EC_START_FAILED}
+		fi
+	;;
 
-    # Print service status.
-    #
-    # This can be invoked by any user and has different exit codes:
-    #   0 - running and OK
-    #   1 - dead and /var/run PID file exists
-    #   2 - dead and /var/lock lock file exists
-    #   3 - not running
-    #   4 - unknown
-    status)
-        status_of_proc "${DAEMON}" "${NAME}" || exit $?
-    ;;
+	# Print service status.
+	#
+	# This can be invoked by any user and has different exit codes:
+	#   0 - running and OK
+	#   1 - dead and /var/run PID file exists
+	#   2 - dead and /var/lock lock file exists
+	#   3 - not running
+	#   4 - unknown
+	status)
+		status_of_proc "${DAEMON}" "${NAME}" || exit $?
+	;;
 
-    # Stop the service, do nothing if it is already stopped.
-    stop)
-        if [ ${STATUS} -eq 0 ]
-        then
-            info 'stopping ...'
-            stop_service || die ${EC_STOP_FAILED}
-        else
-            info 'already stopped.'
-        fi
-    ;;
+	# Stop the service, do nothing if it is already stopped.
+	stop)
+		if [ ${STATUS} -eq 0 ]
+		then
+			info 'stopping ...'
+			stop_service || die ${EC_STOP_FAILED}
+		else
+			info 'already stopped.'
+		fi
+	;;
 
-    # Restart the service, if the service is already running, otherwise do nothing.
-    try-restart)
-        check_privileges
-        if [ ${STATUS} -eq 0 ]
-        then
-            info 'restarting service ...'
-            stop_service || die ${EC_RESTART_STOP_FAILED}
-            sleep 0.1
-            start_service || die ${EC_RESTART_START_FAILED}
-        else
-            info 'service not running, nothing to be done.'
-        fi
-    ;;
+	# Restart the service, if the service is already running, otherwise do nothing.
+	try-restart)
+		check_privileges
+		if [ ${STATUS} -eq 0 ]
+		then
+			info 'restarting service ...'
+			stop_service || die ${EC_RESTART_STOP_FAILED}
+			sleep 0.1
+			start_service || die ${EC_RESTART_START_FAILED}
+		else
+			info 'service not running, nothing to be done.'
+		fi
+	;;
 
-    -h|--help)
-        usage
-    ;;
+	-h|--help)
+		usage
+	;;
 
-    *)
-        fail "action '${ACTION}' not recognized."
-        usage 1>&2
-        exit ${EC_INVALID_ARGUMENT}
-    ;;
+	*)
+		fail "action '${ACTION}' not recognized."
+		usage 1>&2
+		exit ${EC_INVALID_ARGUMENT}
+	;;
 
 esac
 
